# Build worker image (VM template)
image: ubuntu

# Maximum number of concurrent jobs for the project
max_jobs: 3

# Build with Release configuration
configuration: Release

# Build Settings
build:
  parallel: true
  project: src/BufferIO.sln
  verbosity: minimal
